import { Project } from "./types";

export const projects: Project[] = [
  {
    id: "proj-001",
    title: "E-Commerce Platform",
    description:
      "Modern e-commerce solution with real-time inventory management",
    longDescription:
      "A comprehensive e-commerce platform built with Next.js 14, featuring real-time inventory management, payment integration, and an admin dashboard. The platform handles 10,000+ daily transactions and serves 50,000+ active users. Built with performance and scalability in mind, utilizing server-side rendering and incremental static regeneration.",
    technologies: ["Next.js", "TypeScript", "Prisma", "PostgreSQL", "Stripe"],
    category: "Web Application",
    featured: true,
    year: "2023",
    order: 1,
    imageUrl: "/images/keeperapp_logo.png",
  },
  {
    id: "proj-002",
    title: "Task Management App",
    description: "Collaborative task management tool with real-time updates",
    longDescription:
      "A real-time collaborative task management application similar to Trello, built with React and Firebase. Features include drag-and-drop kanban boards, real-time collaboration, team management, and custom workflows. Supports 1000+ concurrent users with instant updates across all devices.",
    technologies: ["React", "Firebase", "Material-UI", "Redux"],
    category: "SaaS",
    featured: true,
    year: "2023",
    order: 2,
    imageUrl: "/images/cat.jpg",
  },
  {
    id: "proj-003",
    title: "Portfolio Builder",
    description: "No-code portfolio website builder for developers",
    longDescription:
      "A drag-and-drop portfolio builder that allows developers to create beautiful portfolio websites without coding. Features include customizable templates, GitHub integration, project showcase, blog functionality, and SEO optimization. Over 5,000 developers have created their portfolios using this platform.",
    technologies: ["Next.js", "TailwindCSS", "Supabase", "Vercel"],
    category: "Tool",
    featured: false,
    year: "2022",
    order: 3,
    imageUrl: "/images/keeperapp_logo.png",
  },
  {
    id: "proj-004",
    title: "AI Code Assistant",
    description: "VS Code extension for AI-powered code suggestions",
    longDescription:
      "An intelligent code assistant extension for Visual Studio Code that provides context-aware code suggestions, automatic documentation, and code refactoring recommendations. Powered by OpenAI's GPT-4, it helps developers write better code faster. Currently used by 10,000+ developers worldwide.",
    technologies: ["TypeScript", "VS Code API", "OpenAI API", "Node.js"],
    category: "Developer Tool",
    featured: true,
    year: "2024",
    order: 4,
  },
  {
    id: "proj-003",
    title: "Portfolio Builder",
    description: "No-code portfolio website builder for developers",
    longDescription:
      "A drag-and-drop portfolio builder that allows developers to create beautiful portfolio websites without coding. Features include customizable templates, GitHub integration, project showcase, blog functionality, and SEO optimization. Over 5,000 developers have created their portfolios using this platform.",
    technologies: ["Next.js", "TailwindCSS", "Supabase", "Vercel"],
    category: "Tool",
    featured: false,
    year: "2022",
    order: 3,
  },
  {
    id: "proj-003",
    title: "Portfolio Builder",
    description: "No-code portfolio website builder for developers",
    longDescription:
      "A drag-and-drop portfolio builder that allows developers to create beautiful portfolio websites without coding. Features include customizable templates, GitHub integration, project showcase, blog functionality, and SEO optimization. Over 5,000 developers have created their portfolios using this platform.",
    technologies: ["Next.js", "TailwindCSS", "Supabase", "Vercel"],
    category: "Tool",
    featured: false,
    year: "2022",
    order: 3,
    imageUrl: "/images/keeperapp_logo.png",
  },
  {
    id: "proj-003",
    title: "Portfolio Builder",
    description: "No-code portfolio website builder for developers",
    longDescription:
      "A drag-and-drop portfolio builder that allows developers to create beautiful portfolio websites without coding. Features include customizable templates, GitHub integration, project showcase, blog functionality, and SEO optimization. Over 5,000 developers have created their portfolios using this platform.",
    technologies: ["Next.js", "TailwindCSS", "Supabase", "Vercel"],
    category: "Tool",
    featured: false,
    year: "2022",
    order: 3,
    imageUrl: "/images/keeperapp_logo.png",
  },
  {
    id: "proj-003",
    title: "Portfolio Builder",
    description: "No-code portfolio website builder for developers",
    longDescription:
      "A drag-and-drop portfolio builder that allows developers to create beautiful portfolio websites without coding. Features include customizable templates, GitHub integration, project showcase, blog functionality, and SEO optimization. Over 5,000 developers have created their portfolios using this platform.",
    technologies: ["Next.js", "TailwindCSS", "Supabase", "Vercel"],
    category: "Tool",
    featured: false,
    year: "2022",
    order: 3,
    imageUrl: "/images/keeperapp_logo.png",
  },
  {
    id: "proj-003",
    title: "Portfolio Builder",
    description: "No-code portfolio website builder for developers",
    longDescription:
      "A drag-and-drop portfolio builder that allows developers to create beautiful portfolio websites without coding. Features include customizable templates, GitHub integration, project showcase, blog functionality, and SEO optimization. Over 5,000 developers have created their portfolios using this platform.",
    technologies: ["Next.js", "TailwindCSS", "Supabase", "Vercel"],
    category: "Tool",
    featured: false,
    year: "2022",
    order: 3,
    imageUrl: "/images/keeperapp_logo.png",
  },
];
